server {
  listen 80;
  server_name roboplace.robotickytabor.cz;

  # public map
  location / {
    proxy_pass http://127.0.0.1:8002;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  # restricted tools
  location /painter {
    allow 127.0.0.1;
    allow 192.168.1.0/24;
    deny all;
    proxy_pass http://127.0.0.1:8003;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /connector {
    allow 127.0.0.1;
    allow 192.168.1.0/24;
    deny all;
    proxy_pass http://127.0.0.1:8001;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /logs {
    allow 127.0.0.1;
    allow 192.168.1.0/24;
    deny all;
    proxy_pass http://127.0.0.1:8004;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
